### PR TITLE
Fix: Switch to native js in isReadable visibility detection

### LINKED ISSUE #292: Switch from jquery to native css for visibility detection in a11y
### Subject of the issue
jQuery seems to be broken in chrome for visibility detection. Chrome seems to work fine on native javascript API

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #292 

### Fix
* Switch to native js in isReadable visibility detection, bug with jquery in chrome

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

File: js/a11y.js [hunk 1]
```diff
@@ -434,11 +434,11 @@ class A11y extends Backbone.Controller {
       : $element;
 
     const isNotVisible = $branch.toArray().some(item => {
-      const $item = $(item);
+      const style = window.getComputedStyle(item)
```
Comment (swashbuck) [inline js/a11y.js:437]: Missing semicolon
```suggestion
      const style = window.getComputedStyle(item);
```

**Review by swashbuck — APPROVED** [review]
👍
