### PR TITLE
Fix: Defer data-ready events

### LINKED ISSUE #698: `data.isReady` not reset on language change
When switching languages, `data.isReady` remains `true` despite the data being reloaded. Depending on the when the call is made, this can cause plugins directly calling `data.whenReady()` to resolve the promise early before models are ready, potentially causing errors.

### PR DESCRIPTION
**Pull request by joe-replin**
When switching language or reloading a course, plugins like trickle, page-level progress, and assessment sometimes run before the course models are fully built. This causes runtime errors (e.g., `findDescendantModels is not a function`) because plugins try to use incomplete model objects.

Originally reported here: https://github.com/adaptlearning/adapt-contrib-languagePicker/issues/120

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
- Possibly fixes #698 & #705 
- Added `await wait.queue()` after `setupModel()` in `triggerDataLoaded()` so all models finish building before firing `app:dataLoaded`
- Removed duplicate event triggers in `onLanguageChange()`; now only triggered after models are ready

[//]: # (List appropriate steps for testing if needed)
### Testing
You might not be able to replicate with a vanilla install of Adapt. I'm guessing it needs a wealth of content & features in it to replicate. Alas, this is how race conditions go. :(
1. Open a course with multiple languages
2. Progress to content using trickle, page-level progress, or assessment
3. Switch languages or reload the page mid-course
4. Check the browser console for errors
5. Confirm all plugins work as expected after switching or reloading

### Additional notes
This update makes sure plugins only run after all models are ready, preventing errors and improving reliability during language changes or reloads.

### CODE REVIEW

File: js/data.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ class Data extends AdaptCollection {
     if (Adapt.get('_isStarted')) {
       Adapt.set('_isStarted', false);
     }
-    this.loadCourseData(language, previousLanguage);
+    await this.loadCourseData(language, previousLanguage);
```
Comment (oliverfoster) [inline js/data.js]: This isn't necessary. 

`onLanguageChange` is triggered by a backbone event, which doesn't wait for promises to complete. So there is nothing waiting for `onLanguageChange` to complete and therefore no need to await the final call to `loadCourseData`. You can let this function-call hang in the breeze.

Equally, leaving this in isn't a problem. It just doesn't do anything.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by ethan-lp — APPROVED** [review]
