### PR TITLE
Fix: Corrected check for jsx template (fixes #224)

### LINKED ISSUE #224: Incorrect jsx template check
### Subject of the issue/enhancement/features
Should be:

if (this.isJSX) {

https://github.com/adaptlearning/adapt-contrib-core/blob/3790f356f1a65f93f880a81db8b21ab29f2de07d/js/views/contentObjectView.js#L40

### Your environment
Latest version

### Steps to reproduce
Doesn't work with jsx menus

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #224 

### Fix
* Corrected check for jsx template

### CODE REVIEW

**Review by joe-allen-89 — APPROVED** [review]

File: js/views/contentObjectView.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ export default class ContentObjectView extends AdaptView {
     const type = this.constructor.type;
     Adapt.trigger(`${type}View:preRender contentObjectView:preRender view:preRender`, this);
 
-    if (this.isReact) {
+    if (this.isJSX) {
```
Comment (StuartNicholls) [inline js/views/contentObjectView.js:40]: @oliverfoster Do we need to make this change to line 150 also?
