### PR TITLE
Fix: Use dangerouslySetInnerHTML to set attribution text in image.jsx (fixes #544)

### LINKED ISSUE #544: Use dangerouslySetInnerHTML to set attribution text in image.jsx
### Subject of the issue
Should use `dangerouslySetInnerHTML` in _image.jsx_ to set the attribution text

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #544 

### Fix
* Use `dangerouslySetInnerHTML` to set the attribution text in _image.jsx_
* Compile attribution text so that we can use helpers

### Testing
1. In a Graphic component, set the `_graphic.attribution` value to:

```
{{a11y_alt_text '$5bn' 'five billion dollars'}}
```

2. The attribution text should read `$5bn` with a hidden aria-label of `five billion dollars`

```
<span class="component__attribution graphic__attribution">
  <span class="component__attribution-inner graphic__attribution-inner">
    <span aria-hidden="true">$5bn</span>
    <span class="aria-label">five billion dollars</span>
  </span>
</span>
```

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

File: templates/image.jsx [hunk 1]
```diff
@@ -49,9 +49,7 @@ export default function Image(props) {
 
       {props.attribution &&
       <span className={prefixClasses(attributionClassNamePrefixes, ['__attribution'])}>
-        <span className={prefixClasses(attributionClassNamePrefixes, ['__attribution-inner'])}>
-          {html(props.attribution)}
-        </span>
+        <span className={prefixClasses(attributionClassNamePrefixes, ['__attribution-inner'])} dangerouslySetInnerHTML={{ __html: compile(props.attribution, props) }} />
```
Comment (guywillis) [inline templates/image.jsx:52]: Not really a requirement, more of a preference. Up to you if you'd like to include.
```suggestion
        <span 
          className={prefixClasses(attributionClassNamePrefixes, ['__attribution-inner'])} 
          dangerouslySetInnerHTML={{ __html: compile(props.attribution, props) }} 
        />
```

**Review by guywillis — APPROVED** [review]
👀
