### PR TITLE
Fix: _isOptional parents with _isOptional children (fixes #303)

### LINKED ISSUE #303: _isOptional/completion bug
### Subject of the issue

In this [pr](https://github.com/adaptlearning/adapt-contrib-core/commit/a1d078a350adfd6cae7d3ff5801c9d29d567745b), code was added to make sure that optional pages work correctly, however it seems to result in forcing optional component to become mandatory in all types of parent, when the parent only has optional children. 

Suggestion: I think it should only do that if the parent is also optional.

line 327

i.e. on a mandatory block with optional, interactive children, you'll see that the block, article and page won't complete unless interactions are complete.

https://github.com/adaptlearning/adapt-contrib-core/blob/a1d078a350adfd6cae7d3ff5801c9d29d567745b/js/models/adaptModel.js#L320-L340

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #303 

When a parent is optional, its completion is only used for plp, wait for the children to complete before completing the parent (i.e. force them to become mandatory).

### Fix
* Only _isOptional parents will now force the children to become mandatory

### CODE REVIEW

File: js/models/adaptModel.js [hunk 1]
```diff
@@ -321,9 +321,12 @@ export default class AdaptModel extends LockingModel {
     let completed = false;
     const children = this.getAvailableChildModels();
     const requireCompletionOf = this.get('_requireCompletionOf');
+    const isParentOptional = this.get('_isOptional');
```
Comment (danielghost) [inline js/models/adaptModel.js:324]:
```suggestion
    const isOptional = this.get('_isOptional');
```

File: js/models/adaptModel.js [hunk 2]
```diff
@@ -321,9 +321,12 @@ export default class AdaptModel extends LockingModel {
...
     const isEveryChildOptional = children.every(child => child.get('_isOptional'));
 
-    if (isEveryChildOptional) {
+    if (isParentOptional && isEveryChildOptional) {
```
Comment (danielghost) [inline js/models/adaptModel.js:327]:
```suggestion
    if (isOptional && isEveryChildOptional) {
```

File: js/models/adaptModel.js [hunk 3]
```diff
@@ -321,9 +321,12 @@ export default class AdaptModel extends LockingModel {
...
+      // As parent is optional, its completion is only used for plp
+      //   wait for the children to complete before completing
```
Comment (danielghost) [inline js/models/adaptModel.js:329]:
```suggestion
      // As model is optional, its completion is only used for plp
      // wait for the children to complete before completing
```

**Review by danielghost — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀
