### PR TITLE
Fix: enforcing type boolean on _isActive (Fixes #523)

### LINKED ISSUE #523: itemModel toggleActive function currently not forcing boolean setting
### Subject of the issue/enhancement/features
_isActive property always expected to be boolean but toggleActive not strictly enforcing this currently

### PR DESCRIPTION
**Pull request by ethan-lp**
_isActive property always expected to be boolean but toggleActive not strictly enforcing this currently

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
enforcing type boolean on _isActive within toggleActive function

### CODE REVIEW

File: js/models/itemModel.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default class ItemModel extends LockingModel {
   }
 
   toggleActive(isActive = !this.get('_isActive')) {
-    this.set('_isActive', isActive);
+    this.set('_isActive', !!isActive);
```
Comment (oliverfoster) [inline js/models/itemModel.js:18]:
```suggestion
    this.set('_isActive', Boolean(isActive));
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

File: js/models/itemModel.js (hunk 1 above)
Comment (oliverfoster) [reply js/models/itemModel.js:18]: Why is this needed? Which bit of code is trying to set it to a non-boolean value?

Comment (ethan-lp) [reply js/models/itemModel.js]: `restoreUserAnswers()` within the `itemsQuestionModel.js` file, we are seeing it is passing a binary value and not boolean.

Comment (oliverfoster) [reply js/models/itemModel.js]: https://github.com/adaptlearning/adapt-contrib-core/blob/de6fcd9c58ad7ed0d793920b048fcb213bdcc980/js/models/itemsQuestionModel.js#L47

Could you please wrap that line in a Boolean() call? As it's the offending cause.

Comment (ethan-lp) [reply js/models/itemModel.js]: Yeah done and understood. Thanks Oliver

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

File: js/models/itemModel.js (hunk 1 above)
Comment (oliverfoster) [reply js/models/itemModel.js]: I'm happy for you to leave your original bit in also in toggleActive.

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by lemmyadams — APPROVED** [review]
