### PR TITLE
Fix: PartlyCorrect feedback fallback values

### LINKED ISSUE #415: Feedback partly correct fallbacks not applying correctly
### Subject of the issue/enhancement/features
The help text for the various feedback options state the fallback value, but this does not match reality

### Your environment
* FW V5.31.16

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #415 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* 'Partly Correct Not Final' feedback should fall back to 'Partly Correct Final' which in turn should fall back to 'Incorrect Final' as per instruction text

### CODE REVIEW

**Review by ethan-lp — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

File: js/models/questionModel.js [hunk 1]
```diff
@@ -291,18 +291,22 @@ class QuestionModel extends ComponentModel {
...
-              ? _feedback._partlyCorrect?.notFinal || _feedback._incorrect?.notFinal || ''
-              : _feedback._partlyCorrect?.final || _feedback._incorrect?.final || ''
+            body
           };
         }
+
         // new style
-        const feedbackPartlyCorrect = !isFinal ? _feedback._partlyCorrectNotFinal || _feedback._incorrectNotFinal : _feedback._partlyCorrectFinal || _feedback._incorrectFinal;
+        const fallbackFeedback = _feedback._partlyCorrectFinal || _feedback._incorrectFinal || ''
+        const feedbackPartlyCorrect = !isFinal ? _feedback._partlyCorrectNotFinal || fallbackFeedback : fallbackFeedback;
```
Comment (oliverfoster) [inline js/models/questionModel.js:308]:
```suggestion
        const finalFeedback = _feedback._partlyCorrectFinal || _feedback._incorrectFinal || '';
        const notFinalFeedback = _feedback._partlyCorrectNotFinal || finalFeedback;
        const feedbackPartlyCorrect = isFinal 
          ? finalFallbackFeedback 
          : notFinalFeedback;
```
Could you do similar to the others? Isolate the oddities so that they're easier to read.

Comment (cahirodoherty-learningpool) [reply js/models/questionModel.js:314]: @oliverfoster I actually ended up refactoring the feedback object building a little bit to reduce code repetition. Could you take a look please and see what you think?
Is the "old style" _feedback.correct the right structure? If this was a typo and there was a missing underscore (i.e. it should be `_feedback._correct` then further simplification would be possible on that switch statement

Comment (oliverfoster) [reply js/models/questionModel.js:314]: Old style: https://github.com/adaptlearning/adapt_framework/blob/21f28212cf8e5635fe7f71d09279917861b9a3f3/src/course/en/components.json#L450-L458

New style: https://github.com/adaptlearning/adapt-contrib-core/pull/223

Comment (oliverfoster) [reply js/models/questionModel.js:314]: You don't seem to have eslint in your editor, or it's not working. I have missing semi-colons on line 304, 313, 315, 320

**Comment by oliverfoster** [comment]
What do you reckon to this https://github.com/adaptlearning/adapt-contrib-core/pull/421 ?

**Review by oliverfoster — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Review by ethan-lp — APPROVED** [review]
